sudo: required
services:
  docker

before_install:
  - docker build -t sanchitverma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t sanchitverma/react-test npm test

after_success:
  - docker build -t sanchitverma/multi-client ./client
  - docker build -t sanchitverma/multi-worker ./worker
  - docker build -t sanchitverma/multi-nginx ./nginx
  - docker build -t sanchitverma/multi-server ./server  
  
  # Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push sanchitverma/multi-client
  - docker push sanchitverma/multi-worker
  - docker push sanchitverma/multi-nginx
  - docker push sanchitverma/multi-server

